services:
  backend:
    build: .
    ports:
      - "8003:8000" 
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql+asyncpg://admin:admin123@postgres:5432/mydb

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:8.6
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.dev      # логин для входа
      PGADMIN_DEFAULT_PASSWORD: admin123          # пароль для входа
      PGADMIN_LISTEN_PORT: 5050
    depends_on:
      - postgres
    ports:
      - "5050:5050"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  pgdata:
